# Generated by Django 5.0.4 on 2024-07-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='content/logos/')),
                ('cover_image1', models.ImageField(upload_to='content/covers/')),
                ('cover_image2', models.ImageField(upload_to='content/covers/')),
                ('cover_image3', models.ImageField(upload_to='content/covers/')),
                ('cover_image4', models.ImageField(upload_to='content/covers/')),
                ('type', models.CharField(max_length=4)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Publisher.content')),
            ],
            bases=('Publisher.content',),
        ),
        migrations.CreateModel(
            name='eBook',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Publisher.content')),
            ],
            bases=('Publisher.content',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Publisher.content')),
            ],
            bases=('Publisher.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publisher.publisher'),
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publisher.category')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publisher.content')),
            ],
            options={
                'unique_together': {('content', 'category')},
            },
        ),
    ]
