# Generated by Django 5.0.4 on 2024-07-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0002_remove_publisher_status_publisher_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_path',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(default='free', max_length=4),
        ),
    ]
