# Generated by Django 5.0.4 on 2024-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0003_content_file_path_alter_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='price',
            field=models.IntegerField(default=None, max_length=9),
        ),
    ]
