# Generated by Django 5.0.4 on 2024-07-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0004_content_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
