# Generated by Django 5.0.4 on 2024-07-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0005_alter_content_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='apk_version',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4),
        ),
    ]
