# Generated by Django 5.0.4 on 2024-07-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0006_content_apk_version_alter_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='apk_version',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
