# Generated by Django 5.0.4 on 2024-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0008_alter_content_apk_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='price',
        ),
        migrations.AlterField(
            model_name='content',
            name='apk_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(default='free', max_length=4),
        ),
    ]
