# Generated by Django 5.0.4 on 2024-07-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0011_alter_content_apk_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='apk_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
