# Generated by Django 5.0.4 on 2024-07-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0014_alter_content_apk_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(default='app', max_length=5),
        ),
    ]
