# Generated by Django 5.0.4 on 2024-07-03 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0015_content_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='price',
        ),
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
