# Generated by Django 5.0.4 on 2024-07-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0016_remove_content_price_content_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
