# Generated by Django 5.0.4 on 2024-07-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0018_supportticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='user',
            new_name='publisher',
        ),
    ]
