# Generated by Django 5.0.4 on 2024-07-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0019_rename_user_supportticket_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
