# Generated by Django 5.0.4 on 2024-07-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactUs',
        ),
    ]
