# Generated by Django 5.0.4 on 2024-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
