# Generated by Django 5.0.4 on 2024-07-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_purchase_ebook_purchase_game_alter_purchase_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
